In [20]:
import numpy as np
import matplotlib.pyplot as plt
import numpy.linalg as la
import scipy.linalg as sla

# Actividad 08: Algebra Lineal y Matrices

---
### Profesor: Juan Marcos Marín
### Nombre: Estefania Zapata
*Métodos computacionales*

---

#1
Escriba tres matrices aleatorias $A$, $B$ y $C$ de $3\times 3$, y demuestre las siguientes relaciones

- $ \mathbf{A}\mathbf{B} \neq \mathbf{B}\mathbf{A} $, en general.
- $ (\mathbf{A}\mathbf{B})\mathbf{C} = \mathbf{A}(\mathbf{B}\mathbf{C}) $.
- $ \mathbf{A}(\mathbf{B} + \mathbf{C}) = \mathbf{A}\mathbf{B} + \mathbf{A}\mathbf{C} $.
- $ (\mathbf{A} + \mathbf{B})\mathbf{C} = \mathbf{A}\mathbf{C} + \mathbf{B}\mathbf{C} $.
- $ (\mathbf{A}\mathbf{B})^\top = \mathbf{B}^\top \mathbf{A}^\top $.
- $ \det(\mathbf{A}\mathbf{B}) = \det(\mathbf{A}) \det(\mathbf{B}) $.
- $ (\mathbf{A}^\top)^\top = \mathbf{A} $.
- $ (c\mathbf{A})^\top = c\mathbf{A}^\top $.
- $ (\mathbf{A} + \mathbf{B})^\top = \mathbf{A}^\top + \mathbf{B}^\top $.



In [21]:
A = np.random.randint(0, 10, (3, 3))
B = np.random.randint(0, 10, (3, 3))
C = np.random.randint(0, 10, (3, 3))
c = 3

print(A)
print(B)
print(C)

[[1 0 4]
 [4 6 8]
 [8 2 2]]
[[2 3 7]
 [5 7 0]
 [7 3 0]]
[[7 3 5]
 [7 3 2]
 [8 2 8]]


In [22]:
print("AB:\n", A @ B)
print("BA:\n", B @ A)
print("¿AB = BA?:", np.allclose(A @ B, B @ A))

print("(AB)C:\n", (A @ B) @ C)
print("A(BC):\n", A @ (B @ C))
print("¿(AB)C = A(BC)?:", np.allclose((A @ B) @ C, A @ (B @ C)))

print("A(B + C):\n", A @ (B + C))
print("AB + AC:\n", A @ B + A @ C)
print("¿A(B+C) = AB + AC?:", np.allclose(A @ (B + C), A @ B + A @ C))

print("(A + B)C:\n", (A + B) @ C)
print("AC + BC:\n", A @ C + B @ C)
print("¿(A + B)C = AC + BC?:", np.allclose((A + B) @ C, A @ C + B @ C))

print("(AB)ᵀ:\n", (A @ B).T)
print("BᵀAᵀ:\n", B.T @ A.T)
print("¿(AB)ᵀ = BᵀAᵀ?:", np.allclose((A @ B).T, B.T @ A.T))

print("det(AB):", la.det(A @ B))
print("det(A)*det(B):", la.det(A) * la.det(B))
print("¿Son iguales?:", np.isclose(la.det(A @ B), la.det(A) * la.det(B)))

print("A:\n", A)
print("(Aᵀ)ᵀ:\n", A.T.T)
print("¿(Aᵀ)ᵀ = A?:", np.allclose(A.T.T, A))

print("(cA)ᵀ:\n", (c * A).T)
print("cAᵀ:\n", c * A.T)
print("¿(cA)ᵀ = cAᵀ?:", np.allclose((c * A).T, c * A.T))

print("(A + B)ᵀ:\n", (A + B).T)
print("Aᵀ + Bᵀ:\n", A.T + B.T)
print("¿(A + B)ᵀ = Aᵀ + Bᵀ?:", np.allclose((A + B).T, A.T + B.T))


AB:
 [[30 15  7]
 [94 78 28]
 [40 44 56]]
BA:
 [[70 32 46]
 [33 42 76]
 [19 18 52]]
¿AB = BA?: False
(AB)C:
 [[ 371  149  236]
 [1428  572  850]
 [1036  364  736]]
A(BC):
 [[ 371  149  236]
 [1428  572  850]
 [1036  364  736]]
¿(AB)C = A(BC)?: True
A(B + C):
 [[ 69  26  44]
 [228 124 124]
 [126  78 116]]
AB + AC:
 [[ 69  26  44]
 [228 124 124]
 [126  78 116]]
¿A(B+C) = AB + AC?: True
(A + B)C:
 [[130  40 109]
 [218  82 135]
 [156  64 101]]
AC + BC:
 [[130  40 109]
 [218  82 135]
 [156  64 101]]
¿(A + B)C = AC + BC?: True
(AB)ᵀ:
 [[30 94 40]
 [15 78 44]
 [ 7 28 56]]
BᵀAᵀ:
 [[30 94 40]
 [15 78 44]
 [ 7 28 56]]
¿(AB)ᵀ = BᵀAᵀ?: True
det(AB): 39032.00000000002
det(A)*det(B): 39031.99999999999
¿Son iguales?: True
A:
 [[1 0 4]
 [4 6 8]
 [8 2 2]]
(Aᵀ)ᵀ:
 [[1 0 4]
 [4 6 8]
 [8 2 2]]
¿(Aᵀ)ᵀ = A?: True
(cA)ᵀ:
 [[ 3 12 24]
 [ 0 18  6]
 [12 24  6]]
cAᵀ:
 [[ 3 12 24]
 [ 0 18  6]
 [12 24  6]]
¿(cA)ᵀ = cAᵀ?: True
(A + B)ᵀ:
 [[ 3  9 15]
 [ 3 13  5]
 [11  8  2]]
Aᵀ + Bᵀ:
 [[ 3  9 15]
 [ 3 13  5]
 [11  8

#2

El **Teorema de Laplace** es un método para calcular el determinante de una matriz cuadrada, particularmente útil para matrices de orden mayor a 2. Este teorema se basa en la expansión del determinante por los elementos de una fila o una columna cualquiera.



$$
\det(A) = \sum_{j=1}^n (-1)^{1+j} a_{1j} M_{1j}
$$

donde:
- $a_{1j}$ es el elemento de la primera fila y columna $j$.
- $M_{1j}$ es el menor asociado al elemento $a_{1j}$, es decir, el determinante de la submatriz de $3 \times 3$ que se obtiene al eliminar la fila 1 y la columna $j$.
- $(-1)^{1+j}$ es el signo correspondiente al cofactor del elemento $a_{1j}$.

Podemos realizar una función recursiva para el cálculo del determinante, sabiendo que el valor del determinante de una matriz de orden uno es el único elemento de esa matriz, y el de una matriz de orden superior a uno es la suma de cada uno de los elementos de una fila o columna por los Adjuntos a ese elemento, como en la función recursiva se emplea la misma función definida el cálculo lo haremos por Menor complementario, un ejemplo desarrollado por la primera fila sería:

$$
   \det (A_{j,j}) =
   \left \{
   \begin{array}{llcl}
      si & j = 1 & \to & a_{1,1} \\
                                 \\
      si & j > 1 & \to & \displaystyle \sum_{k=1}^j \; (-1)^{(1+k)} \cdot a_{1,k} \cdot \det( \alpha_{1,k})
   \end{array}
   \right .
$$

Realice una función que encuentre el determinante de una matriz usando la recursividad aqui planteada, explique explicitamente su código

In [23]:
def determinante_laplace(A):
    """
    Calcula el determinante de una matriz cuadrada usando recursividad
    Ingresa una matriz A
    Retorna el determinante de la matriz A
    """


    if A.shape[0] != A.shape[1]: # Verifico que A sea una matriz cuadrada
        raise ValueError("La matriz debe ser cuadrada para calcular su determinante.")

    n = A.shape[0]  # Número de filas o columnas


    if n == 1: # si n=1 la matriz es de 1x1 y el determinante es ese unico valor
        return A[0, 0]

    if n == 2: # si n= 2, entonces la matriz es 2x2, usamos la fórmula explícita del determinante
        return A[0,0]*A[1,1] - A[0,1]*A[1,0]

    det = 0 # Inicializo el determinante en cero

    for j in range(n):    # Recorro la primera fila
        menor = np.delete(np.delete(A, 0, axis=0), j, axis=1) # Calculamos el menor de A[0, j]
        signo = (-1) ** j # Alternolos signos según la posición
        det_menor = determinante_laplace(menor)    # recursividad para calcular el determinante del menor
        det += signo * A[0, j] * det_menor # Sumo el producto del elemento, el signo y el determinante del menor

    return det



#3 Método de Gauss - Seidel

Sea \$A\in\mathbb{R}^{n\times n}\$ no singular y sea \$b\in\mathbb{R}^n\$.
Descomponga \$A\$ como

$$
A \;=\; D \;+\; L \;+\; U,
$$

donde

* \$D\$ es la matriz diagonal de \$A\$,
* \$L\$ es la parte estrictamente triangular inferior,
* \$U\$ es la parte estrictamente triangular superior.

El algoritmo de Gauss - Seidel reorganiza el sistema \$Ax=b\$ como

$$
x \;=\; (D+L)^{-1}\bigl(b \;-\; Ux\bigr),
$$

y genera la sucesión

$$
x_i^{(k+1)}
= \frac{1}{a_{ii}}
\Bigl(b_i - \sum_{j<i} a_{ij}\,x_j^{(k+1)} - \sum_{j>i} a_{ij}\,x_j^{(k)}\Bigr),
\qquad i=1,\dots,n.
$$

Implemente una función `gauss_seidel(A, b, tol=1e-7, max_iter=100)` que:
   * Realice las iteraciones hasta que
     $\lVert x^{(k+1)}-x^{(k)}\rVert_\infty<\text{tol}$
     o se alcance `max_iter`;
   * devuelva el vector solución aproximado \$x\$, el número de iteraciones realizadas y la norma del último residuo.

Incluya una documentación clara.

Luego,

   * Genere una matriz aleatoria \$5\times5\$ (por ejemplo, con `np.random.rand`) y un vector \$b\$ aleatorio.
   * Resuelva \$Ax=b\$ con su función; calcule el error relativo frente a `numpy.linalg.solve`.
   * Estime igualmente el error respecto a la solución obtenida mediante \$x=A^{-1}b\$ (usando `numpy.linalg.inv`).
   * Presente las normas de los residuos y los errores relativos.

In [24]:
def gauss_seidel(A, b, tol=1e-7, max_iter=100):
    """
    Resuelve el sistema lineal Ax = b usando el método iterativo de Gauss-Seidel.

    Ingresa
    A : matriz cuadrada (n x n)
    b : vector columna tamaño n
    tol :Tolerancia para el criterio de parada.
    max_iter : Máximo número de iteraciones.

    Retorna
    x : vector solución aproximada
    k : número de iteraciones realizadas
    residuo : norma del residuo final
    """
    n = A.shape[0] # número de filas (o columnas)
    x = np.zeros(n) # solución inicial

    for k in range(max_iter):
        x_ant = x.copy()# guarda la solución anterior
        for i in range(n):
            suma1 = np.dot(A[i, :i], x[:i])

            suma2 = np.dot(A[i, i+1:], x_ant[i+1:])
            x[i] = (b[i] - suma1 - suma2) / A[i, i] # Actualiza x[i]

        error = la.norm(x - x_ant, ord=np.inf) # Criterio de parada
        if error < tol:
            break

    residuo = la.norm(b - A @ x, ord=np.inf) #Cálculo del residuo final
    return x, k + 1, residuo


In [25]:
A = np.random.randint(0, 10, size=(5, 5))
b =np.random.randint(0, 10, size=(5, 1))

#soluciones
x_gs, iteraciones, residuo = gauss_seidel(A, b) #Gauss-Seidel
x_exacta = la.solve(A, b) #la.solve
x_inv = la.inv(A) @ b # la.inv

# Errores relativos
error_rel_solve = la.norm(x_gs - x_exacta, ord=np.inf) / la.norm(x_exacta, ord=np.inf)
error_rel_inv = la.norm(x_gs - x_inv, ord=np.inf) / la.norm(x_inv, ord=np.inf)

print("Matriz A:\n", A)
print("Vector b:\n", b)
print("\nSolución con Gauss-Seidel:\n", x_gs)
print("Iteraciones:", iteraciones)
print("Residuo final:", residuo)

print("\nError relativo con respecto a la.solve:", error_rel_solve)
print("Error relativo con respecto a la.inv @ b:", error_rel_inv)


Matriz A:
 [[1 1 1 5 2]
 [8 3 0 3 0]
 [4 3 7 7 6]
 [2 0 0 2 5]
 [6 5 5 5 2]]
Vector b:
 [[5]
 [7]
 [1]
 [4]
 [0]]

Solución con Gauss-Seidel:
 [-7.20802513e+78  4.12365493e+79 -4.18443637e+79 -1.39516575e+80
  3.71935050e+80]
Iteraciones: 100
Residuo final: 3.0141629825113463e+81

Error relativo con respecto a la.solve: 4.5682377671894845e+80
Error relativo con respecto a la.inv @ b: 4.5682377671894835e+80


/tmp/ipython-input-1965715778.py:25: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  x[i] = (b[i] - suma1 - suma2) / A[i, i] # Actualiza x[i]


#4 Método de potencias para el valor propio dominante

Sea \$A\in\mathbb{R}^{n\times n}\$ diagonalizable con valor propio dominante \$\lambda\_{\max}\$ (en magnitud) y vector propio asociado \$v\_{\max}\$.

El método de potencias genera, a partir de un vector inicial \$q^{(0)}\neq 0\$, la sucesión

$$
q^{(k+1)} \;=\; \frac{A\,q^{(k)}}{\lVert A\,q^{(k)}\rVert_2},
\qquad
\lambda^{(k+1)} \;=\; (q^{(k+1)})^{\!\top} A\, q^{(k+1)},
$$

que converge a \$v\_{\max}/\lVert v\_{\max}\rVert\_2\$ y a \$\lambda\_{\max}\$ respectivamente, bajo hipótesis estándar.

Implemente `power_method(A, tol=1e-7, max_iter=1000)` que:

   * Acepte matrices reales cuadradas,
   * Devuelva \$\lambda\_{\max}\$, el vector propio normalizado \$v\_{\max}\$, el número de iteraciones y la última variación relativa de \$\lambda\$,
   * detenga la iteración cuando
     $\bigl|\lambda^{(k+1)}-\lambda^{(k)}\bigr|<\text{tol}\,|\lambda^{(k+1)}|$
     o se alcance `max_iter`.

Luego,
   * Genere una matriz simétrica aleatoria \$6\times6\$ (por ejemplo, \$A = (M+M^\top)/2\$ con \$M\$ aleatoria).
   * Aplique su `power_method` y compare \$\lambda\_{\max}\$ y \$v\_{\max}\$ con los resultados de `numpy.linalg.eig`.

In [26]:
def power_method(A, tol=1e-7, max_iter=1000):
    n = A.shape[0]
    q = np.random.rand(n)
    q = q / la.norm(q)

    lambda_viejo = 0
    for i in range(max_iter):
        Aq = A @ q
        q = Aq / la.norm(Aq)
        lambda_nuevo = q.T @ A @ q

        if abs(lambda_nuevo - lambda_viejo) < tol:
            break
        lambda_viejo = lambda_nuevo

    return lambda_nuevo, q, i+1, abs(lambda_nuevo - lambda_viejo)



In [27]:
M = np.random.randint(0, 10, size=(6, 6))
A = (M + M.T) / 2

lambda_max, v_max, n_iter, ultimo_lambda = power_method(A)

eigvals, eigvecs = la.eig(A)
idx = np.argmax(np.abs(eigvals))
lambda_np = eigvals[idx]
v_np = eigvecs[:, idx]


print("Método de potencias:")
print(f"λ_max = {lambda_max}")
print(f"v_max = {v_max}")
print(f"Iteraciones = {n_iter}, Última diferencia = {ultimo_lambda}")

print("\nCon la.eig:")
print(f"λ_max = {lambda_np}")
print(f"v_max = {v_np / la.norm(v_np)}")

Método de potencias:
λ_max = 23.660918223245297
v_max = [0.29154765 0.4235064  0.36650123 0.27134223 0.58902007 0.42514456]
Iteraciones = 9, Última diferencia = 1.581534903039028e-08

Con la.eig:
λ_max = 23.660918225479328
v_max = [-0.29154339 -0.42350557 -0.36650319 -0.27134543 -0.58902363 -0.42513964]


#5

Verifique que cualquier matriz hermitiana de 2 × 2 $ L $ puede escribirse como una suma de cuatro términos:

$$ L = a\sigma_x + b\sigma_y + c\sigma_z + dI $$

donde $ a $, $ b $, $ c $ y $ d $ son números reales.

Las cuatro matrices de Pauli son:

$$ \sigma_x = \begin{pmatrix} 0 & 1 \\ 1 & 0 \end{pmatrix}, \quad \sigma_y = \begin{pmatrix} 0 & -i \\ i & 0 \end{pmatrix}, \quad \sigma_z = \begin{pmatrix} 1 & 0 \\ 0 & -1 \end{pmatrix}, \quad I = \begin{pmatrix} 1 & 0 \\ 0 & 1 \end{pmatrix} $$




In [28]:
# Matrices de Pauli e identidad
sigma_x = np.array([[0, 1], [1, 0]], dtype=complex)
sigma_y = np.array([[0, -1j], [1j, 0]], dtype=complex)
sigma_z = np.array([[1, 0], [0, -1]], dtype=complex)
I = np.eye(2, dtype=complex)

# Crear una matriz hermitiana arbitraria 2x2
r, s = np.random.rand(2)
z = np.random.rand() + 1j * np.random.rand()
H = np.array([[r, z], [np.conj(z), s]])

# vectorizar las matrices base
basis = np.array([
    sigma_x.reshape(4),
    sigma_y.reshape(4),
    sigma_z.reshape(4),
    I.reshape(4)
]).T.real  # parte real de la base

H_vec = H.reshape(4).real  #la parte real

coeffs = np.linalg.lstsq(basis, H_vec, rcond=None)[0]
a, b, c, d = coeffs
L = a * sigma_x + b * sigma_y + c * sigma_z + d * I

# Verificación
print("Matriz original H:")
print(H)
print("\nMatriz reconstruida L:")
print(L)



Matriz original H:
[[0.41978086+0.j         0.61151371+0.08159418j]
 [0.61151371-0.08159418j 0.25620694+0.j        ]]

Matriz reconstruida L:
[[0.41978086+0.j 0.61151371+0.j]
 [0.61151371+0.j 0.25620694+0.j]]


# 6

Haga un breve resumen en Markdown de las funciones y métodos más relevantes para algebra lineal usando Python. Emplee ejemplos.

##Alguna funciones para algebra lineal usando numpy.linalg as la

- Crear matrices

 - np.array: para crear arreglos de forma definidad (vectores o matrices).
 - np.random.randint(a, b, size = (n,m)) Aqui hago matrices de forma aleatoria

- Algunas operaciones basicas:

 C = A + A (Sumar)

 D = A - A (Restar)

 E = A * A (Multiplicación elemento a elemento)

- np.dot(A, b)         Producto matriz por vector

- np.matmul(A, A)      Producto matriz por matriz

- A @ A               tambien mulitplica matriz por matriz

- Algunas propiedades

 - .T: transpuesta de una matriz.

  - la.det(A)  Determinante

  - la.inv(A) Inversa

  - la.diagonal(A) Extraer la diagonal principal

- valores, vectores = la.eig(A)

 valores: autovalores.

 vectores: autovectores

- algunas matrices utiles
  - np.eye(n) Matriz identidad nxn

  - np.zeros((n, n)) Matriz nxn de ceros

  - np.ones((n, n)) Matriz nx de unos



In [29]:
A = np.array([[2, 3], [1, 4]])
B = np.random.randint(0, 10, size=(2, 2))
v = np.array([5, 6])

print(A)
print(B)
print(v)

[[2 3]
 [1 4]]
[[6 8]
 [3 3]]
[5 6]


In [30]:
suma = A + B
resta = A - B
elemento_a_elemento = A * B
producto_punto = np.dot(A, v)
producto_matriz1 = np.matmul(A, B)
producto_matriz2 = A @ B

print(suma)
print(resta)
print(elemento_a_elemento)
print( producto_punto)
print(producto_matriz1)
print(producto_matriz2)

[[ 8 11]
 [ 4  7]]
[[-4 -5]
 [-2  1]]
[[12 24]
 [ 3 12]]
[28 29]
[[21 25]
 [18 20]]
[[21 25]
 [18 20]]


In [31]:

transpuesta = A.T
det_A = la.det(A)
inv_A = la.inv(A)
diagonal_A = np.diagonal(A)
valores, vectores = la.eig(A)

print(transpuesta)
print(det_A)
print(inv_A)
print(diagonal_A)
print(valores)
print(vectores)

[[2 1]
 [3 4]]
5.000000000000001
[[ 0.8 -0.6]
 [-0.2  0.4]]
[2 4]
[1. 5.]
[[-0.9486833  -0.70710678]
 [ 0.31622777 -0.70710678]]


In [32]:
identidad = np.eye(2)
ceros = np.zeros((2, 2))
unos = np.ones((2, 2))

print(identidad)
print(ceros)
print(unos)


[[1. 0.]
 [0. 1.]]
[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
